---
- name: update package lists
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

- name: add fish repository key
  become: yes
  become_method: sudo
  apt_key: 
    url: https://download.opensuse.org/repositories/shells:fish:release:2/Debian_9.0/Release.key 
    state: present

- name: add fish repository
  become: yes
  become_method: sudo
  apt_repository: 
    repo: 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_9.0/ /' 
    state: present 
    filename: fish
    update_cache: yes

- name: install common packages
  become: yes
  become_method: sudo
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - fish
    - git
    - htop
    - jq
    - tree

- name: upgrade all packages
  become: yes
  become_method: sudo
  apt:
    upgrade: dist

- name: change shell to fish
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish

- name: create peterbourgon dir
  file:
    path: "$HOME/src/github.com/peterbourgon"
    state: directory

- name: clone dotfiles repo
  git:
    repo: git@github.com:peterbourgon/dotfiles
    dest: "$HOME/src/github.com/peterbourgon/dotfiles"
    accept_hostkey: yes

- name: run dotfiles install
  command: ./install.fish
  args: 
    chdir: "$HOME/src/github.com/peterbourgon/dotfiles"
