---
- name: update package lists
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

- name: add fish repository key
  become: yes
  become_method: sudo
  apt_key: 
    url: https://download.opensuse.org/repositories/shells:fish:release:2/Debian_9.0/Release.key 
    state: present

- name: add fish repository
  become: yes
  become_method: sudo
  apt_repository: 
    repo: 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_9.0/ /' 
    state: present 
    filename: fish
    update_cache: yes

- name: install common packages
  become: yes
  become_method: sudo
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - fish
    - git
    - htop
    - jq
    - tree

- name: upgrade all packages
  become: yes
  become_method: sudo
  apt:
    upgrade: dist

- name: add user pb
  become: yes
  become_method: sudo
  user:
    name: pb
    shell: /usr/bin/fish
    groups: sudo

- name: add authorized key
  become: yes
  become_method: sudo
  authorized_key: 
    user: pb
    key: "{{ lookup('file', 'pb_key.pub') }}"
    state: present

- name: create peterbourgon dir
  remote_user: pb
  file:
    path: /home/pb/src/github.com/peterbourgon
    state: directory

- name: clone dotfiles repo
  remote_user: pb
  git:
    repo: git@github.com:peterbourgon/dotfiles
    dest: /home/pb/src/github.com/peterbourgon/dotfiles
    accept_hostkey: yes

- name: run dotfiles install
  remote_user: pb
  command: ./install.fish
  args: 
    chdir: /home/pb/src/github.com/peterbourgon/dotfiles
